### ISSUE TITLE
Fail to build and install plugin "hppmonitoringplugin"

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-plot#11]
https://github.com/humanoid-path-planner/hpp-plot/blob/d10a8f5ce612b700def47ac76325fcbddb8b1a6d/plugins/CMakeLists.txt#L29
Neither `GEPETTO_VIEWER_CORBA_FOUND`, nor `gepetto_viewer_corba_FOUND` are set to true although gepetto-viewer-corba is a required dependency.

https://github.com/humanoid-path-planner/hpp-plot/blob/d10a8f5ce612b700def47ac76325fcbddb8b1a6d/plugins/CMakeLists.txt#L30
This variable is not defined either.

Moreover, running cmake on this project as on others results in thousands of lines of output.

**Comment by jmirabel** [comment]
I had uncommited changes on my laptop. This may fix your issue: bb3de5c.

**Comment by jmirabel** [comment]
> Moreover, running cmake on this project as on others results in thousands of lines of output.

This should be solved by https://github.com/jrl-umi3218/jrl-cmakemodules/pull/375. I am waiting for people to react.

**Comment by jmirabel** [comment]
You may hit this too: https://github.com/humanoid-path-planner/hpp-manipulation-corba/issues/92

**Comment by nim65s** [comment]
is is not `gepetto_viewer_corba_FOUND` but `gepetto-viewer-corba_FOUND`, as we are asking for the `gepetto-viewer-corba` package.

**Comment by nim65s** [comment]
Fixed by #12
